# Generated by Django 5.0.1 on 2024-01-25 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_customuser_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.batches",
            ),
        ),
    ]
