# Generated by Django 5.0.1 on 2024-01-26 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_customuser_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("no_of_days", models.IntegerField()),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("file_url", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
