# Generated by Django 5.0.1 on 2024-01-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_internships"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extracurriculur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=100)),
                ("event_organiser", models.CharField(max_length=70)),
                ("event_date", models.CharField(max_length=20)),
                ("event_type", models.CharField(max_length=30)),
                ("event_level", models.CharField(max_length=30)),
                ("event_position", models.CharField(max_length=30)),
                ("file_url", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extrac",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mooc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=100)),
                ("course_type", models.CharField(max_length=50)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("file_url", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mooc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
