# Generated by Django 5.0.1 on 2024-01-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_extracurriculur_mooc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("organiser", models.CharField(max_length=100)),
                ("no_of_days", models.IntegerField()),
                ("date", models.CharField(max_length=50)),
                ("file_url", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
