# Generated by Django 5.0.1 on 2024-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_customuser_is_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
