# Generated by Django 5.0.1 on 2024-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customuser_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='registration_number',
            new_name='roll_number',
        ),
    ]
