# Generated by Django 5.0.1 on 2024-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_registration_number_customuser_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('ECE', 'Eletronics and Communication'), ('CSE', 'Computer Science'), ('MH', 'Mechanical Engineering')], default='ECE', max_length=6),
        ),
    ]
