# Generated by Django 5.0.1 on 2024-09-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_batch_college_alter_customuser_batch_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workshop_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
