# Generated by Django 5.0.1 on 2024-12-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_batch_college_alter_customuser_batch_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_address',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='guardian_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_remarks',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default='B22ECA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.TextField(default='Kollam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(default='TKMCE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('advisor', 'Advisor'), ('student', 'Student')], default='Student', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='ECE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='website.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='website.college'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='website.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=30, null=True)),
                ('roll_number', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian', models.CharField(blank=True, max_length=40, null=True)),
                ('guardian_no', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='website.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
