# Generated by Django 5.1.4 on 2024-12-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='advisor_profile',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_advisor', to='website.advisor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_profile',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customuser_student', to='website.student'),
        ),
    ]
