# Generated by Django 5.1.4 on 2024-12-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_advisor_user_remove_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='advisor_profile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_profile',
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
