# Generated by Django 5.1.4 on 2024-12-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_customuser_advisor_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurriculur',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internships',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mooc',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshops',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
