# Generated by Django 5.0.1 on 2024-12-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_customuser_workshop_url'),
        ('website', '0016_extracurriculur_is_approved_internships_is_approved_and_more'),
    ]

    operations = [
    ]
