# Generated by Django 5.0.1 on 2024-12-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_merge_20241216_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='workshop_url',
        ),
    ]
