# Generated by Django 5.1.4 on 2024-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_customuser_workshop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
