# Generated by Django 5.1.4 on 2024-12-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_student_gdrive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurriculur',
            name='ktu_points',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internships',
            name='ktu_points',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mooc',
            name='ktu_points',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshops',
            name='ktu_points',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
