# Generated by Django 5.1.4 on 2024-12-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_extracurriculur_ktu_points_internships_ktu_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurriculur',
            name='ktu_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='ktu_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mooc',
            name='ktu_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='ktu_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
