# Generated by Django 5.1.4 on 2024-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_extracurriculur_ktu_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ktu_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
